/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../config/keys.ts" />
/// <reference path="../config/controls.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../objects/vector2.ts" />
/// <reference path="../objects/tiles/tile.ts" />
/// <reference path="../objects/tiles/groundtile.ts" />
/// <reference path="../objects/tiles/tiletypes.ts" />
/// <reference path="../objects/tiles/emerald.ts" />
/// <reference path="../objects/gameobjects/motobug.ts" />
/// <reference path="../objects/gameobjects/crabmeat.ts" />
/// <reference path="../objects/gameobjects/spike.ts" />
/// <reference path="../objects/gameobjects/rock.ts" />
/// <reference path="../objects/gameobjects/player.ts" />
/// <reference path="../objects/gameobjects/gameobject.ts" />
/// <reference path="../objects/gameobjects/physgameobject.ts" />
/// <reference path="../objects/gameobjects/pathswitcher.ts" />
/// <reference path="../managers/collision.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/level.ts" />
/// <reference path="../scenes/testroom.ts" />
/// <reference path="../scenes/instructions.ts" />
/// <reference path="../scenes/greenhillzone.ts" />
//# sourceMappingURL=_reference.js.map